name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
      working-directory: src/
      
    - name: Run Pytest
      run: |
        pytest tests/
      working-directory: src/
