name: LaTeX Linting with TeXtidote

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11' # TeXtidote requires Java

    - name: Run TeXtidote
      run: |
        wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.2/textidote.jar

    - name: Install Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    
    - name: Run textidote with reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        find 03_Final_report_and_presentation -name "*.tex" -exec java -jar textidote.jar --check en --output singleline {} \; \
          | reviewdog -efm="%f(L%lC%c-*): %m" -name="textidote" -reporter=github-pr-review
      
